### ISSUE TITLE
Error on console 2.4.0

### ISSUE THREAD

**Issue by Dyrnwyrm** [krbz999/templatemacro#10]
![image](https://github.com/krbz999/templatemacro/assets/129613553/6d6aae11-184c-45ce-87de-b2b74d9b64f9)

Tried deleting tokens even nuking for testing (since Midi protects bad tokens from dying) nothing worked

**Comment by krbz999** [comment]
That there is an error in the console is not enough to take any action. When opening an issue, you have to provide steps to reproduce as well. Additionally, you should disable all other modules to determine whether it is even caused by *this* module.

**Comment by Dyrnwyrm** [comment]
Sorry now i know what triggers the error, if a player moves a token on a scene that the DM is not looking the error pops up, Actives Auras and Rideable had similar errors that got fixed

**Comment by krbz999** [comment]
Comment from @chrisk123999
> When a token is moved on a scene that isn't being viewed, this error pops up in the console. This is likely cause from the token object not existing when the scene on the update isn't the same one as the viewed scene.
