### ISSUE TITLE
Feature Request: Initial event which could contain "global" variables/functions to prevent duplications in between events code

### ISSUE THREAD

**Issue by sasquach45932** [krbz999/templatemacro#3]

**Comment by krbz999** [comment]
Example please.

**Comment by sasquach45932** [comment]
1. You want to execute a macro when a token enters and leaves the template  both macros refers to the very same function. If this function could be moved to  the "Initial" event you do not need to duplicate it twice.
2. Creating global variables e.g.:

let API = game.modules.get("templatemacro").api;
let targets = API.findContained(template);
let origin = template.flags.dnd5e.origin;
let item = await fromUuid(origin);
let SpellDC = item.parent.system.attributes.spelldc;
const SaveType = item.system.save.ability;
const SpellName = item.name;

**Comment by krbz999** [comment]
I think simply implementing a method in the API to call a specific trigger's template macro (like is implemented in Effect Macro) would do the job. You would then have the script in the 'leaving' trigger, and the 'entering' trigger would have a one-liner to call that script as well.

**Comment by sasquach45932** [comment]
Yes it could an option as well but I think a new event would be better it is more futureproof. 
Thanks for the fast reaction and for useful modules.

**Comment by krbz999** [comment]
As for example (2), storing variables, I would suggest simply using flags on the template to store them for later. Doing that during template creation should be a trivial matter. If I were to implement that in the module, it would be what I did anyhow, and that wouldn't be able to cover all use cases. The user doing that themselves seems like the ideal.

**Comment by sasquach45932** [comment]
You are right, storing varibales is an excellen idea.
