### ISSUE TITLE
Feature Request: System Agnostic

### ISSUE THREAD

**Issue by Potatozuli** [krbz999/templatemacro#4]
I noticed that this has an undisclosed DnD5e dependency. I only found one place in the code where it directly references DnD, and I tried hacking it myself to run it in a non-DnD system. From my testing, the macro triggering appears to work, although for some reason functions like findContained or findContainers don't function. From what I can tell it wouldn't be that much modification to make this system-agnostic, although it seems a bit beyond me without breaking something.

**Comment by krbz999** [comment]
This is something I had planned to do, thanks for the reminder.
